version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10100:8080'
    restart: unless-stopped
    volumes:
      - './configs/dev.yaml:/app/configs/dev.yaml'
    entrypoint: './main'
    networks:
      finances:
        aliases:
          - backend
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2016001
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "1001:5432"

networks:
  finances:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
